version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin: ["*"]
    Access-Control-Allow-Headers: ["Authorization", "X-Requested-With", "Content-Type"]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
