name: Deploy to GitHub Pages

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]
    types: [ closed ]

jobs:
  deploy:
    # Only run on push OR when PR is merged
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        NODE_ENV: production